
server:
  error:
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dioproject
    username: root
    password: a87015726
  jpa:
    hibernate:
      ddl_auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
